name: Preset

on:
  workflow_call:
    inputs:

jobs:
  preset-node:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ^7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: pnpm
      - run: |
          pushd backend
          pnpm install --frozen-lockfile
          popd
          pushd frontend
          pnpm install --frozen-lockfile
          popd
