#!/usr/bin/env bash

CURRENT_DIR="$(dirname "$(realpath "$0")")";
PROJECT_DIR="$(realpath "$CURRENT_DIR/../../")"
TMP_DIR=/tmp_navig8

function frontend {
  pushd "$PROJECT_DIR"
    pnpm build
    mv index.html dist/index.template.html
    mv .env.template dist/.env.template
    mv dist "$TMP_DIR/frontend"
  popd
}

function ejs_renderer {
  pushd "$PROJECT_DIR"
    pnpm i -s html-prettify ejs ramda.pipe

    pushd "$CURRENT_DIR"
      ncc build -m -q -C render_index.mjs
      rm render_index.mjs
      mv dist/index.mjs render_index.mjs
      rm -rf dist
    popd
  popd
}

pnpm install --frozen-lockfile

mkdir $TMP_DIR

frontend;
ejs_renderer;

rm "$CURRENT_DIR/prepare"
mv "$PROJECT_DIR/docker" "$TMP_DIR/docker"
pushd /
  rm -rf "$PROJECT_DIR"
  mv "$TMP_DIR" "$PROJECT_DIR"
popd
