#!/usr/bin/env bash

CURRENT_DIR="$(dirname "$(realpath "$0")")";
PROJECT_DIR="$(realpath "$CURRENT_DIR/../../")"

DEFAULT_NAVIG8_CORS_PROXY_URL=/proxy/
export NAVIG8_CORS_PROXY_URL=${NAVIG8_CORS_PROXY_URL:-/proxy/}

#######################################
# Generates necessary files for the frontend to support env variables handling from the RUN stage
# Globals:
#   CURRENT_DIR
#   PROJECT_DIR
# Globals for subcommands:
#   All variables from 'frontend/.env.template'
# Arguments:
#   Name of the env object in js
#   Name of the env file
#######################################
function gen_frontend {
  local FRONTEND_DIR="$(realpath "$PROJECT_DIR/frontend")"

  local ENV_NAMES=($(grep -o '^[a-zA-Z0-9_]*=' "$FRONTEND_DIR/.env.template" | sed 's/.$//'))
  local FILE_NAME="${1:-"env.runtime.js"}"
  local FILE_PATH="${FRONTEND_DIR}/dist/${FILE_NAME}"

  # Create config file
  rm -f "$FILE_PATH"
  touch "$FILE_PATH"

  # Add assignments
  echo "window._env_ = {" >> "$FILE_PATH"

  for varname in "${ENV_NAMES[@]}"
  do
    value=$(printf '%s\n' "${!varname}" | sed -e 's/\x27/\\\x27/g')
    # If there is a value set, pass it to a file
    [[ -n $value ]] && echo "  $varname: '$value'," >> "$FILE_PATH"
  done

  echo "};" >> "$FILE_PATH"

  # Render index.html's ejs template
  NAVIG8_TOP_HEAD="${NAVIG8_TOP_HEAD}
    <script src=\"${FILE_NAME}\"></script>" \
    node \
    --no-deprecation \
    "$CURRENT_DIR/render_index.cjs";

  echo 'Generated env for frontend'

  pnpm remove -s html-prettify ejs ramda.pipe
}

#######################################
# Starts nginx server with reverse proxy to CORS proxy
#######################################
function start_nginx_with_cors_proxy {
  local BACKEND_DIR="$(realpath "$PROJECT_DIR/backend")"
  pushd $BACKEND_DIR && pnpm run-daemon && popd || exit

  echo 'CORS proxy started'

  cp "$PROJECT_DIR/docker/nginx.with_cors_proxy.conf" /etc/nginx/sites-available/default
  /usr/sbin/nginx -g 'daemon off;';
}

#######################################
# Starts nginx server
#######################################
function start_nginx {
  cp "$PROJECT_DIR/docker/nginx.conf" /etc/nginx/sites-available/default
  /usr/sbin/nginx -g 'daemon off;';
}

# Generate frontend runtime env and index.html
gen_frontend env.runtime.js;

# Default CORS proxy server
if [ "$DEFAULT_NAVIG8_CORS_PROXY_URL" = "$NAVIG8_CORS_PROXY_URL" ]; then
  start_nginx_with_cors_proxy;
else
  start_nginx;
fi
