name: Publish Docker image

on:
#  release:
#    types: [published]
  create:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get-npm-version
        id: version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: frontend

      - name: Log in to Github Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          load: true
#          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }},test_tag,${{ steps.meta.outputs.version || steps.version.outputs.current-version }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: test
        run: |
          docker image inspect test_tag;
